### ISSUE TITLE
Multi-manifest Support

### ISSUE THREAD

**Issue by lander2k2** [nukleros/gener8s#1]
Currently the `gener8s go` command only supports a single manifest in a YAML document.  This issue is to propose allowing multiple manifests which will produce multiple objects generated in output.

For example:
```
# +gener8s:var:sampleNamespace
apiVersion: v1
kind: Namespace
metadata:
  name: go-web3-sample-app
---
# +gener8s:var:sampleConfig
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-web3-sample-app-config
  namespace: go-web3-sample-app
data:
  RPCENDPOINT: http://forward-proxy.forward-proxy-system.svc.cluster.local
```

Included here are markers that allow the variable name to be specified for each object.  Order of priority would be:
* object name supplied in marker
* variable name supplied by `-v` flag (used for all objects without a marker)
* default variable name: `resourceObj`

In the case that a var name is passed with `-v` flag _and_ a marker is supplied, we can emit a warning that informs the user that the marker var name will be used.
